import type { Sermon } from "@/types";

export const MOCK_SERMONS: Sermon[] = [
  { id: "1", title: "Yeshu Ente Nalla Edayan | Malayalam Christian Song", speaker: "Jenin Varghese", series: "Worship Songs", description: "New Malayalam Christian song 2026 featuring Jenin Varghese.", youtube_url: "https://youtube.com/watch?v=-UUkiZ_QWbg", thumbnail_url: null, duration_seconds: 315, sermon_date: "2026-06-10", tags: ["worship", "malayalam", "music"], view_count: 5240, created_at: "2026-06-10T11:00:00Z" },
  { id: "2", title: "Holy Are You Lord | Christian Worship Song", speaker: "Jenin Varghese", series: "Worship Songs", description: "Christian Worship Song 2026 by Jenin Varghese.", youtube_url: "https://youtube.com/watch?v=sqIJuD8j0rs", thumbnail_url: null, duration_seconds: 280, sermon_date: "2026-06-05", tags: ["worship", "english", "music"], view_count: 3103, created_at: "2026-06-05T09:00:00Z" },
  { id: "3", title: "Live Prayer & Worship | Session 1", speaker: "Reni Peter", series: "Intercessory Prayer", description: "Live Intercessory Prayer for Nations.", youtube_url: "https://youtube.com/watch?v=6lVArzrCxmQ", thumbnail_url: null, duration_seconds: 7200, sermon_date: "2026-05-28", tags: ["prayer", "worship", "live"], view_count: 8421, created_at: "2026-05-28T09:00:00Z" },
  { id: "4", title: "Chahu Tujhe Kal Se Bhi Zyada | Hindi Worship", speaker: "Reni Peter", series: "Worship Songs", description: "New Hindi Worship Song Official Video.", youtube_url: "https://youtube.com/watch?v=OZ0JYVSvgzs", thumbnail_url: null, duration_seconds: 420, sermon_date: "2026-05-20", tags: ["worship", "hindi", "music"], view_count: 11954, created_at: "2026-05-20T09:00:00Z" },
  { id: "5", title: "Chahu Tujhe Kal Se Bhi Zyada | Trailer", speaker: "Reni Peter", series: "Worship Songs", description: "Official Trailer for the new Hindi worship song.", youtube_url: "https://youtube.com/watch?v=7rtV33Onlm8", thumbnail_url: null, duration_seconds: 60, sermon_date: "2026-05-15", tags: ["trailer", "worship"], view_count: 2122, created_at: "2026-05-15T09:00:00Z" },
  { id: "6", title: "Yeshu Ente Nalla Edayan | Lyrics", speaker: "Jenin Varghese", series: "Worship Songs", description: "Lyric video for Yeshu Ente Nalla Edayan.", youtube_url: "https://youtube.com/watch?v=-UUkiZ_QWbg", thumbnail_url: null, duration_seconds: 315, sermon_date: "2026-05-10", tags: ["lyrics", "worship"], view_count: 1811, created_at: "2026-05-10T09:00:00Z" },
];
