import type { Sermon } from "@/types";

export const MOCK_SERMONS: Sermon[] = [
  { id: "1", title: "When God Moves in the Valley", speaker: "Pastor David Mitchell", series: "Mountains & Valleys", description: "A powerful message about trusting God in your lowest seasons.", youtube_url: "https://www.youtube.com/@agapeinternationalmedia", thumbnail_url: null, duration_seconds: 2820, sermon_date: "2026-06-08", tags: ["faith", "valley", "trust"], view_count: 1847, created_at: "2026-06-08T11:00:00Z" },
  { id: "2", title: "The Power of Community", speaker: "Pastor Sarah Mitchell", series: "We Are One", description: "Why belonging to a church family changes everything.", youtube_url: "https://www.youtube.com/@agapeinternationalmedia", thumbnail_url: null, duration_seconds: 2340, sermon_date: "2026-06-01", tags: ["community", "belonging"], view_count: 2103, created_at: "2026-06-01T09:00:00Z" },
  { id: "3", title: "Radical Generosity", speaker: "Pastor David Mitchell", series: "Kingdom Economy", description: "What the Bible truly says about giving and abundance.", youtube_url: "https://www.youtube.com/@agapeinternationalmedia", thumbnail_url: null, duration_seconds: 3060, sermon_date: "2026-05-25", tags: ["giving", "generosity"], view_count: 3421, created_at: "2026-05-25T09:00:00Z" },
  { id: "4", title: "Surrender Everything", speaker: "Pastor Sarah Mitchell", series: "Mountains & Valleys", description: "What it truly means to let God be in control of your entire life.", youtube_url: "https://www.youtube.com/@agapeinternationalmedia", thumbnail_url: null, duration_seconds: 2580, sermon_date: "2026-05-18", tags: ["surrender", "faith"], view_count: 1954, created_at: "2026-05-18T09:00:00Z" },
  { id: "5", title: "The Spirit of Adoption", speaker: "Pastor David Mitchell", series: "Identity", description: "You are a child of God — and that changes everything.", youtube_url: "https://www.youtube.com/@agapeinternationalmedia", thumbnail_url: null, duration_seconds: 2700, sermon_date: "2026-05-11", tags: ["identity", "adoption"], view_count: 4122, created_at: "2026-05-11T09:00:00Z" },
  { id: "6", title: "Faith Over Fear", speaker: "Pastor David Mitchell", series: "Identity", description: "How to walk boldly in faith even when fear is real.", youtube_url: "https://www.youtube.com/@agapeinternationalmedia", thumbnail_url: null, duration_seconds: 2460, sermon_date: "2026-05-04", tags: ["faith", "fear"], view_count: 2811, created_at: "2026-05-04T09:00:00Z" },
];
